if(UNISTRING_INCLUDE_DIR)
    set(UNISTRING_FIND_QUIETLY TRUE)
endif(UNISTRING_INCLUDE_DIR)

find_path(UNISTRING_INCLUDE_DIR unistr.h)

set(UNISTRING_NAMES unistring libunistring)
find_library(UNISTRING_LIBRARY NAMES ${UNISTRING_NAMES})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(UNISTRING DEFAULT_MSG UNISTRING_INCLUDE_DIR UNISTRING_LIBRARY)

mark_as_advanced(UNISTRING_LIBRARY UNISTRING_INCLUDE_DIR UNISTRING_LIBRARY)
